EarTrumpet/EarTrumpet.csproj
EarTrumpet/Extensions/DoubleExtensions.cs
EarTrumpet/Extensions/SliderExtensions.cs
EarTrumpet/MainWindow.xaml
EarTrumpet/MainWindow.xaml.cs

New version of the slider mousewheel event that should better "fit in" with the rest of the project. 
Also used the newly added [double].Bound(min,max) in the SetPositionByControlPoint function instead of the rather complicated bounding with the ternary operator.

Slider mousewheel event

---

EarTrumpet/ViewModels/AppItemViewModel.cs

I noticed that when you mute from the native Windows volume mixer that EarTrumpet's internal state becomes out of sync. This change fixes it and should avoid any other problems with mismatching state.

fix mismatch when muting from W10 volume mixer

---

EarTrumpet/TrayIcon.cs
EarTrumpet/ViewModels/TrayIconViewModel.cs

Hello fellow volume control replacement app makers. A long time ago I wrote a similar but less advanced app, where the primary feature was middle clicking the tray icon to toggle mute. I missed this a lot when trying out EarTrumpet, so here I am with this feature so I can permanently switch. Thanks!

Add middle click tray icon to toggle mute

---

EarTrumpet/Services/TaskbarService.cs

Previously, the taskbar size was calculated as follows: The taskbar size in pixels was retrieved, then the taskbar size in points was retrieved. The scaling factor was calculated based on these, which the taskbar size in points was multiplied by to get the final value to be used (pixels).
Since we already retrieved the taskbar size in pixels, just use that instead to avoid the unnecessary calculations. This fixes #181.
Tested at 100% DPI and 150% DPI on all screen edges, with and without auto-hide, with no regressions observed.

Simplify taskbar size calculations

---

EarTrumpet/Interop/NotifyIconData.cs
EarTrumpet/UI/Helpers/ShellNotifyIcon.cs

Fixes the issues in #460:
1. `NOTIFYICONDATAW` struct now has the correct layout, so `uVersion` is seen correctly as `NOTIFYICON_VERSION_4` by the shell
2. `uFlags` now has `NIF_SHOWTIP` so that the standard tooltip is still displayed with `NOTIFYICON_VERSION_4`
3. Tracks context menu state so that the multiple messages from the shell (due to `NOTIFYICON_VERSION_4`) on right-click do not cause the context menu to open and immediately close.
This might also fix the GUID handling, but I see that was removed recently.

Fix NOTIFYICONDATA struct layout and fallout

---

EarTrumpet/EarTrumpet.csproj

When testing the new localization I noticed that 0cf9988f17faf13626d65b499ca23acf08050b6e forgot to add references to the new resources so I fixed that.

Add missing RESX references to project

---

EarTrumpet/EarTrumpet.csproj
EarTrumpet/prebuild.ps1

This fixes the build commands when running in directories with spaces. Targeted against dev this time.

Fix cmds running against directories with spaces

---

EarTrumpet/UI/Helpers/TaskbarIconSource.cs
EarTrumpet/UI/ViewModels/DeviceViewModel.cs
EarTrumpet/UI/Views/DeviceView.xaml

Microsoft is slowly changing the way they represent unmuted devices with a volume level of zero. This change aligns EarTrumpet behavior with expected behavior.
Windows 10, as of 21313.rs_prerelease.210209-1440, yields inconsistent results:
| Notification Area Icon 	| Flyout 	|
|------------------------	|--------	|
| 0 bars                 	| 1 bar  	|
EarTrumpet 2.1.8.0 behavior:
| Notification Area Icon 	| Flyout 	|
|------------------------	|--------	|
| 1 bar                 	| 1 bar  	|
EarTrumpet vNext behavior (this PR):
| Notification Area Icon 	| Flyout 	|
|------------------------	|--------	|
| 0 bars                 	| 0 bar  	|

Show zero-bar icon variant when device volume level at zero (fixes #478)

---

README.md

Now that `winget` is shipping with windows by default, it should be listed in the readme.

mention `winget` in readme

---

EarTrumpet/UI/Views/FlyoutWindow.xaml.cs

Added missing calculations for flyout positioning when an offset was applied, resulting in an inaccessible flyout header.
Fixes #1121

Compensate for flyout pos offset in calculations

---

EarTrumpet/App.xaml.cs
EarTrumpet/AppSettings.cs
EarTrumpet/Properties/Resources.Designer.cs
EarTrumpet/Properties/Resources.resx
EarTrumpet/UI/ViewModels/AudioSessionViewModel.cs
EarTrumpet/UI/ViewModels/EarTrumpetShortcutsPageViewModel.cs
EarTrumpet/UI/Views/SettingsWindow.xaml

An user can register 2 keys to control volume globally across all devices. A user muting a device with "normal" control cannot unmute with absolute control to prevent unwanted unmute.
The function `AbsoluteVolumeIncrement` and `AbsoluteVolumeDecrement` are in `App.xaml.xs` because I did not know if a new dedicated file is wanted for a such small addition or not. Tell me if you want to change the architecture to a cleaner structure.
The `absMuted` property is not set in the stream level because I did not see the value to set this low in the architecture. It is only needed by AudioSession. Again, I can change the location if wanted.
Compilation and run:
Fixes: #831

For #831: Absolute volume control

---

EarTrumpet/App.xaml

EarTrumpet's light theme is not very consistent with native flyouts and is very difficult to see with particular accent colors.
| Before | After |
| ------------- | ------------- |

Improved consistency with Light Theme

---

EarTrumpet/Interop/Helpers/WindowsTaskbar.cs
EarTrumpet/UI/Helpers/WindowAnimationLibrary.cs
EarTrumpet/UI/ViewModels/FlyoutViewModel.cs
EarTrumpet/UI/Views/FlyoutWindow.xaml.cs

This should mitigate the bug introduced in 19H1+ which slows down windows with acrylic effect applied using the undocumented API.
Also fixes an issue when flyout animation was showing above the taskbar when there are no active windows and the issue when flyout was overlapping the taskbar after animation end (often happens with fractional DPI scale factors, e.g. 125%).
Might need to test on Windows 11 to see how this affects the animation, as there is no acrylic bug in Windows 11.
| Before | After |
| ------------- | ------------- |
Related issues: #391

Improve flyout entrace animation

---

EarTrumpet/App.xaml.cs
EarTrumpet/AppSettings.cs
EarTrumpet/EarTrumpet.csproj
EarTrumpet/Interop/Helpers/MouseHook.cs
EarTrumpet/Interop/User32.cs
EarTrumpet/Properties/Resources.Designer.cs
EarTrumpet/Properties/Resources.resx
EarTrumpet/UI/ViewModels/EarTrumpetMouseSettingsPageViewModel.cs
EarTrumpet/UI/ViewModels/FlyoutViewModel.cs
EarTrumpet/UI/ViewModels/IFlyoutViewModel.cs
EarTrumpet/UI/Views/FlyoutWindow.xaml.cs
EarTrumpet/UI/Views/SettingsWindow.xaml

This PR adds "Extra settings" page with setting "Scroll anywhere to change volume when EarTrumpet is open". When it's turned on it will allow user to change system volume with mouse scroll when cursor isn't over the EarTrumpet window, just like regular volume control in Windows 10.
Discussion #658.
Issue #208.

Scroll anywhere to change volume while EarTrumpet is open (discussion #658)

---

EarTrumpet/Interop/Helpers/HotkeyData.cs
EarTrumpet/UI/ViewModels/HotkeyViewModel.cs

Took a crack at #703. Wasn't sure if I should open a separate issue since there's already a request in discussions so sending this PR 
The main wrinkle with using the Windows key as a modifier is that it's not actually one according to the Windows API. This means that it doesn't have a nice value to use as a bitmask like `Keys.Control`, `Keys.Alt`, and `Keys.Shift` do. In fact there's a warning in the [`System.Windows.Forms.Keys` docs](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.keys?view=netframework-4.6.2#remarks) about this:
> Do not use the values in this enumeration for combined bitwise operations. The values in the enumeration are not mutually exclusive.
Looking at the actual values on that page, the modifiers' bits won't overlap with anything else while `LWin` …

Allow Windows key in shortcuts (Discussion #703)

---

EarTrumpet/App.xaml.cs
EarTrumpet/Interop/Helpers/WindowsTaskbar.cs
EarTrumpet/Interop/User32.cs

This obtains tooltip window handle by sending `TB_GETTOOLTIPS` message to the tray and requests it to update (i.e. sends `TTM_POPUP`, so it shows again), making it display the current volume level when adjusting using mouse wheel scroll
https://user-images.githubusercontent.com/51774833/215256566-ba2c5b0c-0b50-49a2-bc03-21fc6ce35192.mp4

Update tray icon tooltip on wheel scroll

---

EarTrumpet/App.xaml.cs

There is some inconsistency while updating tray tooltip currently. This pull request should fix it.
https://github.com/File-New-Project/EarTrumpet/assets/8844478/ad1869ff-430b-478b-b546-73de3a6fe82d

Update tray tooltip more consistently

---

EarTrumpet/App.xaml.cs

It looks like this would be a better solution to consistently update the tooltip as the tooltip would be updated also when the volume is changed with hotkeys, the default device is muted/unmuted or when the default playback device is changed.

Update tray tooltip on device mute or default device change

---

EarTrumpet/DataModel/WindowsAudio/Internal/AudioDeviceManager.cs

This is a fairly simple edit to correct the behaviour of AudioDeviceManager.GetDefaultDevice to use the eRole parameter passed rather than always return the eMultimedia device.
See issue #1494

Fix AudioDeviceManager.GetDefaultDevice to use eRole Parameter

---

.github/workflows/translators.yml
CONTRIBUTING.md
README.md

This pull request introduces automation for updating the `README.md` file with a list of localization contributors fetched from the CrowdIn API, and provides guidance for translators on how to get listed in the `README.md`.
- Adds a new GitHub Actions workflow file `.github/workflows/translators.yml` that:
- Runs weekly to fetch the list of localization contributors using the CrowdIn API.
- Updates the `README.md` file with the fetched list, placing translator avatars and names in the newly added "Translators" section.
- Utilizes a secret `CROWDIN_API_TOKEN` for API authorization.
- Sorts translators alphabetically by full name before updating the README.
- Modifies `README.md` to:
- Include a placeholder comment `` where the list of translators will be dynamically inserted.
- Updates …

Add translators to README

---

EarTrumpet/Interop/Helpers/WindowsTaskbar.cs
EarTrumpet/NativeMethods.txt
EarTrumpet/UI/Views/FlyoutWindow.xaml.cs

StartAllBack provides support for per-taskbar notification area. Shell APIs would return active (last clicked) taskbar.
- Get active taskbar rect via ABM_GETTASKBARPOS with special flag; use that rect to get monitor instead of primary tray monitor
- Get taskbar DPI via proper API which would account for active / auto-hidden taskbar
- Readjust popup window position by repeating its calculation with new DPI to account for DPI changes
#1611

Support for StartAllBack multitaskbar notification area

---

EarTrumpet/Interop/Helpers/IconHelper.cs
EarTrumpet/NativeMethods.txt
EarTrumpet/UI/Controls/ImageEx.cs

- Using LoadIconWithScaleDown will ensure better-looking icon at non-standard DPI
- Notification area can update app icon itself for proper DPI if GetIconInfoEx will return proper module path; this doesn't work for LOAD_LIBRARY_AS_IMAGE_RESOURCE or LOAD_LIBRARY_AS_DATAFILE mapping unfortunately so use DONT_RESOLVE_DLL_REFERENCES
#495

Fix scenarios where icon is blurry

---

EarTrumpet/App.xaml.cs
EarTrumpet/DataModel/Audio/IAudioDeviceManager.cs
EarTrumpet/DataModel/WindowsAudio/Internal/AudioDeviceManager.cs

Try to workaround part of the issues in File-New-Project/EarTrumpet#1305 that applications disappear when users login back after user switching.
The workaround try to detect user re-connecting to its login session and do a refresh (delete and re-create) its device list.
Although it does not fix the root cause of the issue, I have been using this workaround for several months it does help to resolve my use case. Please consider accepting this when the real fix is not ready yet.

Workaround to File-New-Project/EarTrumpet#1305 (part of)

---

CHANGELOG.md
EarTrumpet/App.xaml.cs
EarTrumpet/AppSettings.cs
EarTrumpet/DataModel/Audio/Mocks/AudioDevice.cs
EarTrumpet/DataModel/Audio/Mocks/AudioDeviceSession.cs
EarTrumpet/DataModel/WindowsAudio/Internal/AudioDevice.cs
EarTrumpet/DataModel/WindowsAudio/Internal/AudioDeviceChannel.cs
EarTrumpet/DataModel/WindowsAudio/Internal/AudioDeviceSession.cs
EarTrumpet/Extensions/FloatExtensions.cs
EarTrumpet/Properties/Resources.Designer.cs
EarTrumpet/Properties/Resources.resx
EarTrumpet/UI/Controls/VolumeSlider.cs
EarTrumpet/UI/Converters/NegateConverter.cs
EarTrumpet/UI/Converters/VolumeToStringConverter.cs
EarTrumpet/UI/ViewModels/AudioSessionViewModel.cs
EarTrumpet/UI/ViewModels/DeviceCollectionViewModel.cs
EarTrumpet/UI/ViewModels/DeviceViewModel.cs
EarTrumpet/UI/ViewModels/EarTrumpetCommunitySettingsPageViewModel.cs
EarTrumpet/UI/ViewModels/IAppItemViewModel.cs
EarTrumpet/UI/ViewModels/SettingsAppItemViewModel.cs
EarTrumpet/UI/ViewModels/TemporaryAppItemViewModel.cs
EarTrumpet/UI/Views/AppItemView.xaml
EarTrumpet/UI/Views/DeviceView.xaml
EarTrumpet/UI/Views/SettingsWindow.xaml

Related issue #1703 
All features mentioned in that issue are implemented.
- Logarithmic peak meter
- dB value on label instead of percent
- Adjustable logarithmic slider range (current default: 40 dB, range 12 to 96 dB)
- This is meant to be calibrated by the user to their barely audible level
- Hot reload internal and UI state when certain settings are changed
- Now uses logarithmic API for device volume, because SetMasterVolumeScalar is non-linear and we will get wrong result if we treat it as linear then compute log value based on it. Sessions are still work with linear API since they only have a linear API.
- Changed some view models' Volume field from int to float.
- ~~Channels don't automatically get muted when slider is at the minimum, this is by design, not a bug, since it's …

Reimplementation of logarithmic volume
